services:
  - type: web
    name: Render-Dashboard
    runtime: docker
    region: oregon
    buildCommand: |
      mix deps.get --only prod
      MIX_ENV=prod mix compile
      MIX_ENV=prod mix assets.setup
      MIX_ENV=prod mix assets.deploy
      MIX_ENV=prod mix release
    startCommand: |
      PHX_SERVER=true PORT=$PORT _build/prod/rel/render_dashboard/bin/render_dashboard start
    envVars:
      - key: SECRET_KEY_BASE
        sync: false

